RD-50039 Check required inputs
https://finalcad.atlassian.net/wiki/spaces/INFRA/pages/4764532737/Naming+labelling#Strategy
https://finalcad.atlassian.net/browse/RD-50039

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,10 +10,10 @@ inputs:
     default: 'eu-central-1'
   environment:
     description: 'Finalcad envrionment: production, staging, sandbox'
-    require: true
+    required: true
   owner:
     description: 'Team owner of the repository'
-    default: ''
+    required: true
   product:
     description: 'Product name'
     default: 'finalcad-one'
@@ -26,6 +26,27 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Pre-conditition
+      shell: bash
+      run: |
+        rc=0
+        [[ ! -z '${{ inputs.aws-role}}' ]] || {
+          rc=$?
+          echo 'Missing Github action input "aws-role"'
+        }
+        [[ ! -z '${{ inputs.environment}}' ]] || {
+          rc=$?
+          echo 'Missing Github action input "environment"'
+        }
+        [[ ! -z '${{ inputs.owner}}' ]] || {
+          rc=$?
+          echo 'Missing Github action input "owner"'
+        }
+        [[ ! -z '${{ inputs.registry}}' ]] || {
+          rc=$?
+          echo 'Missing Github action input "registry"'
+        }
+        exit $rc
     - name: Configure AWS credentials for security
       uses: aws-actions/configure-aws-credentials@v5
       with:
